Repository cedar-policy/cedar, pull requests merged in 2024-03, with the labels that each got.

#707 Refactoring in integration testing code
  Cargo.toml
  cedar-policy/CHANGELOG.md
  cedar-policy/src/lib.rs
  cedar-testing/Cargo.toml
  cedar-testing/README.md
  cedar-testing/src/cedar_test_impl.rs
  cedar-testing/src/integration_testing.rs
  cedar-testing/src/lib.rs
  cedar-testing/tests/cedar-policy-cli/corpus_tests.rs
  cedar-testing/tests/cedar-policy-cli/decimal.rs
  cedar-testing/tests/cedar-policy-cli/example_use_cases.rs
  cedar-testing/tests/cedar-policy-cli/ip.rs
  cedar-testing/tests/cedar-policy-cli/main.rs
  cedar-testing/tests/cedar-policy-cli/multi.rs
  cedar-testing/tests/cedar-policy/corpus_tests.rs
  cedar-testing/tests/cedar-policy/decimal.rs
  cedar-testing/tests/cedar-policy/example_use_cases.rs
  cedar-testing/tests/cedar-policy/ip.rs
  cedar-testing/tests/cedar-policy/multi.rs
Labels: 3.2

#715 refactor: remove unnecessary lifetimes from validation related structs
  cedar-policy/CHANGELOG.md
  cedar-policy/src/api.rs
Labels: 4.0, breaking-change

#677 Refactor the handling of negative numbers in CST to EST conversion
  cedar-policy-core/src/est.rs
  cedar-policy-core/src/est/expr.rs
Labels: 4.0, breaking-change

#716 Move `ImpossiblePolicy` from error to warning
  cedar-policy-validator/src/lib.rs
  cedar-policy-validator/src/rbac.rs
  cedar-policy-validator/src/str_checks.rs
  cedar-policy-validator/src/type_error.rs
  cedar-policy-validator/src/typecheck.rs
  cedar-policy-validator/src/typecheck/test_namespace.rs
  cedar-policy-validator/src/typecheck/test_optional_attributes.rs
  cedar-policy-validator/src/typecheck/test_partial.rs
  cedar-policy-validator/src/typecheck/test_policy.rs
  cedar-policy-validator/src/typecheck/test_utils.rs
  cedar-policy-validator/src/validation_result.rs
  cedar-policy/CHANGELOG.md
  cedar-policy/src/frontend/validate.rs
Labels: 3.2

#750 [CLI] default to human schema format
  cedar-policy-cli/CHANGELOG.md
  cedar-policy-cli/src/lib.rs
Labels: breaking-change

#749 Strengthen the types of `SchemaFragment`
  cedar-policy-core/src/ast/name.rs
  cedar-policy-validator/src/coreschema.rs
  cedar-policy-validator/src/err.rs
  cedar-policy-validator/src/human_schema/ast.rs
  cedar-policy-validator/src/human_schema/err.rs
  cedar-policy-validator/src/human_schema/fmt.rs
  cedar-policy-validator/src/human_schema/test.rs
  cedar-policy-validator/src/human_schema/to_json_schema.rs
  cedar-policy-validator/src/lib.rs
  cedar-policy-validator/src/rbac.rs
  cedar-policy-validator/src/schema.rs
  cedar-policy-validator/src/schema/namespace_def.rs
  cedar-policy-validator/src/schema_file_format.rs
  cedar-policy-validator/src/typecheck/test_expr.rs
  cedar-policy/src/api.rs
Labels: breaking-change
